### ISSUE TITLE
Is ember_app/styles mandatory?

### ISSUE THREAD

**Issue by fullofcaffeine** [rwz/ember-cli-rails#192]
Hi!

I don't want to keep styles in the `ember_app/styles` directory because I already use the Rails assets pipeline for that. However, if I remove this directory, `ember-cli` fails with:

```
EmberCLI::App::BuildError (EmberCLI app "frontend" has failed to build):
  Error: ENOENT: no such file or directory, scandir 'frontend/tmp/tree_merger-tmp_dest_dir-wElhzwrD.tmp/app/styles/'
      at Error (native)
      at Object.fs.readdirSync (fs.js:813:18)
      at walkSync (frontend/node_modules/ember-cli/node_modules/walk-sync/index.js:14:20)
      at Funnel.processFilters (frontend/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:113:15)
      at Funnel.rebuild (frontend/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:108:10)
      at frontend/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:42:21
      at lib$rsvp$$internal$$tryCatch (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
      at frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
      at lib$rsvp$asap$$flush (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

What are the best practices when it comes to CSS stylesheets? Should they all be moved to `ember_app/styles`? I'm a bit confused here, if someone could enlighten me, I'd be grateful!

**Comment by fullofcaffeine** [comment]
Nevermind, I decided to just move all my styles from the Rails assets pipeline to ember-cli's assets pipeline, and it works great :)
