### ISSUE TITLE
Problem with compiling assets on Heroku

### ISSUE THREAD

**Issue by Szeliga** [rwz/ember-cli-rails#211]
Hi,

I have a problem compiling assets on heroku. I have two ember apps and they both live in `Rails.root/ember/app1` and `Rails.root/ember/app2`. When trying to build it on heroku, I get the following error:

```
remote:        Build failed.
remote:        ENOENT, no such file or directory 'tests'
remote:        Error: ENOENT, no such file or directory 'tests'
remote:        at Error (native)
remote:        at Object.fs.lstatSync (fs.js:792:18)
remote:        at symlink (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
remote:        at symlinkOrCopySync (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
remote:        at /tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:58:9
remote:        at lib$rsvp$$internal$$tryCatch (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
remote:        at lib$rsvp$$internal$$invokeCallback (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
remote:        at lib$rsvp$$internal$$publish (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
remote:        at lib$rsvp$asap$$flush (/tmp/build_00c9efe5d815cf0aecdc9f61a48fa834/ember/app1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
remote:        at process._tickCallback (node.js:355:11)
remote:        rake aborted!
```

I've followed the guide to setup the repo for heroku deployment.

`Rails.root/package.json`
```
{
  "cacheDirectories": [
    "node_modules",
    "vendor/assets/components",
    "ember/app1/node_modules",
    "ember/app1/bower_components",
    "ember/app2/node_modules",
    "ember/app2/bower_components"
  ],
  "dependencies": {
    "bower": "*"
  }
}

```

I've ran out of ideas how to fix this. To the best of my knowledge ember-cli is trying to run the tests when building and there is some mismatch in directories, because it can't find `tests` dir.

Is it possible to disable running the tests? Because I already run them in CI, so there is no need to do it again.

Or am I missing the point entirely?

Best regards,
Szymon

**Comment by Szeliga** [comment]
Turns out that we had a `.slugignore` file that pointed both ember apps' tests directories for removal, for compression purposes. After removing the folders the build was successful
